#!/bin/bash

if ($1 eq 'true'); then
    echo 'Executing in parallel browsers'
    npx dotenv npx testcafe -c 5 'browserstack:ie@11.0:Windows 10','browserstack:chrome@83.0:OS X Catalina' ./tests
else
    echo 'Execute tests on Safari'
    npx dotenv npx testcafe "browserstack:safari@11.1:OS X High Sierra" ./tests
fi
